"""Desk runtime: wires config -> clients -> gateway -> engines for the CLI.

On this Linux environment only `SimMt5Client` is possible; every real-terminal
code path first checks `real_client_available()` and reports USER-ACTION
instead of pretending. Sim market data is generated by a clearly-labelled
seeded random walk — it is simulation, never presented as broker data.
"""

from __future__ import annotations

import getpass
import random
import time
from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from aegis_velocity.arming import ARMING_PHRASE, validate_token, write_token
from aegis_velocity.audit.auditor import Auditor
from aegis_velocity.consensus.council import Council, CouncilInputs
from aegis_velocity.core.anchors import EquityAnchors, PersistedCounters, PersistedState
from aegis_velocity.core.clock import BrokerClock
from aegis_velocity.core.config import DeskConfig, TradingMode, load_desk_config
from aegis_velocity.core.ledger import Ledger
from aegis_velocity.core.security import mask_login
from aegis_velocity.cost.calendar import NewsCalendar, import_calendar_csv
from aegis_velocity.cost.engine import CostEngine
from aegis_velocity.cost.liquidity import SpreadHistory
from aegis_velocity.execution.idempotency import IntentStore
from aegis_velocity.mt5.gateway import P2_ACCOUNT, P3_DATA, Mt5Gateway
from aegis_velocity.mt5.protocol import Bar, Mt5Client, Tick
from aegis_velocity.mt5.real import real_client_available
from aegis_velocity.mt5.recorder import TickRecorder, load_recorded_ticks
from aegis_velocity.mt5.sim import SimMt5Client, default_spec
from aegis_velocity.mt5.symbols import (
    discover_symbols,
    measure_scalp_eligibility,
    persist_eligibility,
    persist_symbol_map,
)
from aegis_velocity.risk.commander import RiskCommander
from aegis_velocity.strategies import STRATEGY_REGISTRY
from aegis_velocity.strategies.base import StrategyContext

TickCallback = Callable[[str, Tick], None]


@dataclass
class Desk:
    root: Path
    cfg: DeskConfig
    mode: TradingMode
    client: Mt5Client
    gateway: Mt5Gateway
    ledger: Ledger
    intents: IntentStore
    clock: BrokerClock
    cost_engine: CostEngine
    council: Council
    risk: RiskCommander
    auditor: Auditor
    recorder: TickRecorder
    is_sim: bool

    def stop(self) -> None:
        self.auditor.stop()
        self.gateway.stop()
        self.ledger.close()


def make_sim_client(cfg: DeskConfig) -> SimMt5Client:
    specs = {name: default_spec(name) for name in cfg.symbols.universe}
    return SimMt5Client(specs=specs, balance=10_000.0)


def build_desk(root: Path, mode: TradingMode) -> Desk:
    cfg = load_desk_config(root)
    data = root / "data"
    data.mkdir(exist_ok=True)

    available, _detail = real_client_available()
    if available:  # pragma: no cover - Windows-only path
        from aegis_velocity.mt5.real import RealMt5Client

        client: Mt5Client = RealMt5Client()
        is_sim = False
        login = cfg.env.login or 0
        password = cfg.env.password.get_secret_value() if cfg.env.password else ""
        server = cfg.env.server
    else:
        sim = make_sim_client(cfg)
        client = sim
        is_sim = True
        login, password, server = sim.login, "sim", sim.server

    if not client.initialize(cfg.env.terminal_path, login, password, server):
        raise RuntimeError(f"MT5 initialize failed: {client.last_error()}")

    gateway = Mt5Gateway(client)
    gateway.start()
    ledger = Ledger(data / "aegis_velocity.db", journal_path=data / "journal.jsonl")
    intents = IntentStore(ledger.connection, ledger.db_lock)
    clock = BrokerClock(persist_path=data / "clock.json")
    calendar = NewsCalendar(data / "calendar.json", cfg.sessions.news_blackout)
    spreads = SpreadHistory(persist_path=data / "spreads.json",
                            history_days=cfg.costs.liquidity_window.history_days)
    cost_engine = CostEngine(cfg.costs, cfg.risk, cfg.sessions, calendar, spreads)
    council = Council(cost_engine=cost_engine, risk_cfg=cfg.risk, clock=clock)
    anchors = EquityAnchors(PersistedState(data / "anchors.json"))
    counters = PersistedCounters(PersistedState(data / "counters.json"))
    risk = RiskCommander(cfg.risk, cfg.correlations, anchors, counters, mode)
    auditor = Auditor(ledger)
    auditor.start()
    recorder = TickRecorder(data / "ticks")
    return Desk(
        root=root, cfg=cfg, mode=mode, client=client, gateway=gateway, ledger=ledger,
        intents=intents, clock=clock, cost_engine=cost_engine, council=council,
        risk=risk, auditor=auditor, recorder=recorder, is_sim=is_sim,
    )


# --------------------------------------------------------------------- helpers


def _sim_walk(
    sim: SimMt5Client,
    symbols: list[str],
    steps: int,
    seed: int = 42,
    spreads: SpreadHistory | None = None,
    on_tick: TickCallback | None = None,
) -> None:
    """Deterministic seeded random walk. SIMULATION DATA, labelled as such.
    `on_tick` receives EVERY scripted tick synchronously (no pump sampling)."""
    rng = random.Random(seed)
    prices = {s: (155.0 if s.endswith("JPY") else 2400.0 if s == "XAUUSD" else 1.10)
              for s in symbols}
    for _ in range(steps):
        for symbol in symbols:
            spec = sim.specs[symbol]
            point = spec.point
            drift = rng.gauss(0, 6) * point
            prices[symbol] = max(prices[symbol] + drift, 100 * point)
            spread_pts = max(4, min(14, round(rng.gauss(8, 2))))
            bid = round(prices[symbol], spec.digits)
            ask = round(bid + spread_pts * point, spec.digits)
            tick = sim.push_tick(symbol, bid, ask, advance_s=1.0)
            if spreads is not None:
                spreads.record(symbol, tick.time, spread_pts)
            if on_tick is not None:
                on_tick(symbol, tick)


def _sim_bars(sim: SimMt5Client, symbol: str, tf_s: int, count: int) -> None:
    spec = sim.specs[symbol]
    base = 155.0 if symbol.endswith("JPY") else 2400.0 if symbol == "XAUUSD" else 1.10
    rng = random.Random(hash(symbol) & 0xFFFF)
    bars = []
    t0 = sim.server_time - timedelta(seconds=tf_s * (count + 1))
    price = base
    for i in range(count):
        o = price
        h = o + abs(rng.gauss(0, 20)) * spec.point
        low = o - abs(rng.gauss(0, 20)) * spec.point
        c = rng.uniform(low, h)
        bars.append(Bar(time=t0 + timedelta(seconds=tf_s * i), open=o, high=h, low=low,
                        close=c))
        price = c
    sim.set_bars(symbol, tf_s, bars)


# ------------------------------------------------------------------- commands


def connect_and_report(root: Path) -> int:  # pragma: no cover - real terminal only
    cfg = load_desk_config(root)
    from aegis_velocity.mt5.real import RealMt5Client

    client = RealMt5Client()
    password = cfg.env.password.get_secret_value() if cfg.env.password else ""
    if not client.initialize(cfg.env.terminal_path, cfg.env.login or 0, password,
                             cfg.env.server):
        print(f"initialize failed: {client.last_error()}")
        return 1
    info = client.account_info()
    if info is None:
        print("no account info")
        return 1
    print(
        f"connected: login={mask_login(info.login)} server={info.server} "
        f"currency={info.currency} margin_mode={info.margin_mode} "
        f"trade_mode={info.trade_mode} trade_allowed={info.trade_allowed}"
    )
    if info.margin_mode != "HEDGING":
        print("REFUSED for execution: netting account (SHADOW analysis only).")
    client.shutdown()
    return 0


def discover_symbols_cli(root: Path) -> int:
    desk = build_desk(root, TradingMode.SHADOW)
    try:
        names = desk.gateway.call(P3_DATA, "symbols_get_names")
        result = discover_symbols(names, desk.cfg.symbols.universe)
        persist_symbol_map(root / "data" / "symbol_map.json", result.mapping)
        print(f"mapped {len(result.mapping)}/{len(desk.cfg.symbols.universe)} symbols"
              + (" [SIM]" if desk.is_sim else ""))
        for canonical, broker in sorted(result.mapping.items()):
            print(f"  {canonical} -> {broker}")
        for canonical, options in result.ambiguous.items():
            print(f"  AMBIGUOUS {canonical}: {options} (confirm manually)")
        for missing in result.missing:
            print(f"  MISSING {missing}")
        desk.ledger.append("symbol_discovery", {
            "mapping": result.mapping, "ambiguous": result.ambiguous,
            "missing": result.missing, "sim": desk.is_sim,
        })
        return 0
    finally:
        desk.stop()


def scalp_eligibility_cli(root: Path) -> int:
    desk = build_desk(root, TradingMode.SHADOW)
    try:
        window_minutes = 5.0
        if desk.is_sim:
            sim = desk.client
            assert isinstance(sim, SimMt5Client)
            _sim_walk(sim, desk.cfg.symbols.universe, steps=int(window_minutes * 60))
        verdicts = []
        for symbol in desk.cfg.symbols.universe:
            spec = desk.gateway.call(P3_DATA, "symbol_info", symbol)
            if spec is None:
                continue
            since = datetime.now(UTC) - timedelta(days=2)
            ticks = desk.gateway.call(P3_DATA, "copy_ticks_from", symbol, since, 100_000)
            samples = [t.spread_points(spec.point) * 1.0 for t in ticks]
            verdict = measure_scalp_eligibility(
                spec, samples, window_minutes, desk.cfg.symbols.scalp_eligibility
            )
            verdicts.append(verdict)
            state = "ELIGIBLE" if verdict.eligible else "DISQUALIFIED"
            print(f"  {symbol}: {state} spread_p50={verdict.spread_p50_points:.1f} "
                  f"ticks/min={verdict.ticks_per_minute:.1f} "
                  f"stops={verdict.stops_level_points} {verdict.reasons}")
        persist_eligibility(root / "data" / "scalp_eligibility.json", verdicts)
        print(("[SIM] " if desk.is_sim else "") + "verdicts written to "
              "data/scalp_eligibility.json")
        return 0
    finally:
        desk.stop()


def record_ticks_cli(root: Path, hours: float) -> int:
    desk = build_desk(root, TradingMode.SHADOW)
    try:
        if desk.is_sim:
            sim = desk.client
            assert isinstance(sim, SimMt5Client)
            steps = int(hours * 3600)
            print(f"[SIM] recording {steps} scripted ticks per symbol "
                  "(simulation data, not broker data)")
            desk.gateway.subscribe_ticks(desk.recorder.on_tick)
            desk.gateway._pump_symbols = list(desk.cfg.symbols.universe)
            for s in desk.cfg.symbols.universe:
                desk.gateway.call(P3_DATA, "symbol_select", s, True)
            import threading

            pump = threading.Thread(target=desk.gateway._run_pump, daemon=True)
            pump.start()
            _sim_walk(sim, desk.cfg.symbols.universe, steps=min(steps, 600))
            time.sleep(0.5)
        else:  # pragma: no cover - real terminal only
            for s in desk.cfg.symbols.universe:
                desk.gateway.call(P3_DATA, "symbol_select", s, True)
            desk.gateway.subscribe_ticks(desk.recorder.on_tick)
            deadline = time.monotonic() + hours * 3600
            while time.monotonic() < deadline:
                time.sleep(1.0)
        desk.recorder.close()
        print(f"recorded tick counts: {desk.recorder.counts}")
        return 0
    finally:
        desk.stop()


def run_desk_cli(root: Path, mode: str, duration_s: float) -> int:
    trading_mode = TradingMode(mode.upper())
    desk = build_desk(root, trading_mode)
    try:
        return _scan_loop(desk, duration_s)
    finally:
        desk.stop()


def _scan_loop(desk: Desk, duration_s: float) -> int:
    """Shadow/demo scan: ticks -> strategies -> council -> ledger. In SHADOW no
    order is ever sent (preflight hard-blocks); this loop only records truth."""
    symbols = desk.cfg.symbols.universe
    for s in symbols:
        desk.gateway.call(P3_DATA, "symbol_select", s, True)
    windows: dict[str, list[Tick]] = {s: [] for s in symbols}
    cooldown_until: dict[tuple[str, str], datetime] = {}
    decisions = 0
    signals_seen = 0

    def on_tick(symbol: str, tick: Tick) -> None:
        nonlocal decisions, signals_seen
        desk.clock.observe_tick(tick.time)
        desk.recorder.on_tick(symbol, tick)
        spec = desk.client.symbol_info(symbol)
        if spec is None:
            return
        window = windows[symbol]
        window.append(tick)
        if len(window) > 200:
            del window[: len(window) - 200]
        if len(window) < 70:
            return
        bars = tuple(desk.client.copy_rates(symbol, 300, 48))
        for sid, strategy_cfg in desk.cfg.strategies.strategies.items():
            if not strategy_cfg.enabled:
                continue
            until = cooldown_until.get((sid, symbol))
            if until is not None and tick.time < until:
                continue  # per-symbol strategy cooldown (§7 declaration)
            ctx = StrategyContext(
                strategy_id=sid, symbol=symbol, spec=spec, ticks=tuple(window),
                bars=bars, server_now=tick.time, cfg=strategy_cfg,
            )
            for signal in STRATEGY_REGISTRY[sid](ctx):
                signals_seen += 1
                cooldown_until[(sid, symbol)] = tick.time + timedelta(
                    seconds=strategy_cfg.cooldown_s
                )
                desk.ledger.append(
                    "signal", signal.model_dump(mode="json"),
                    correlation_id=signal.correlation_id,
                )
                result = desk.council.decide(
                    CouncilInputs(
                        signal=signal, spec=spec, tick=tick, server_now=tick.time,
                        data_integrity=95.0, conflicting_position=False,
                        in_flight_intent=False, strategy_quarantined=False,
                    )
                )
                decisions += 1
                desk.ledger.append(
                    "decision", result.decision.model_dump(mode="json"),
                    correlation_id=signal.correlation_id,
                )

    if desk.is_sim:
        sim = desk.client
        assert isinstance(sim, SimMt5Client)
        for s in symbols:
            _sim_bars(sim, s, 300, 60)
        steps = int(duration_s) if duration_s > 0 else 300
        print(f"[SIM] {desk.mode.value} scan over {steps} scripted ticks/symbol "
              "(simulation data)")
        # every scripted tick is delivered synchronously: deterministic scan
        _sim_walk(sim, list(symbols), steps=steps, spreads=desk.cost_engine.spreads,
                  on_tick=on_tick)
    else:  # pragma: no cover - real terminal only
        desk.gateway.subscribe_ticks(on_tick)
        desk.gateway._pump_symbols = list(symbols)
        import threading

        pump = threading.Thread(target=desk.gateway._run_pump, daemon=True)
        pump.start()
        deadline = time.monotonic() + (duration_s or 3600.0)
        while time.monotonic() < deadline:
            time.sleep(1.0)

    desk.ledger.append(
        "scan_summary",
        {"mode": desk.mode.value, "signals": signals_seen, "decisions": decisions,
         "sim": desk.is_sim},
    )
    verify = desk.ledger.verify()
    print(
        f"scan done: {signals_seen} signals, {decisions} decisions recorded; "
        f"ledger {'OK' if verify.ok else 'BROKEN'} ({verify.rows} rows)"
    )
    return 0


def emergency_stop_cli(root: Path, flatten: bool) -> int:
    """Emergency stop: halt entries, invalidate arming, optionally flatten."""
    from aegis_velocity.arming import disarm

    data = root / "data"
    disarm(data / "arming.json", reason="emergency-stop")
    ledger = Ledger(data / "aegis_velocity.db")
    ledger.append("halt", {"reason": "EMERGENCY_STOP", "flatten": flatten,
                           "source": "cli"})
    ledger.close()
    print("EMERGENCY STOP recorded: arming invalidated, entries halted.")
    if flatten:
        print("flatten requested: on a live host the desk closes all AEG positions"
              " and cancels pendings via gateway P0 + EA flatten_all command.")
    return 0


def report_cli(root: Path, which: str) -> int:
    ledger = Ledger(root / "data" / "aegis_velocity.db")
    try:
        if which == "parity-check":
            print("run: python3 -m pytest tests/test_parity.py -q")
            return 0
        kinds = {
            "report": None,
            "cost-report": "decision",
            "latency-report": "execution",
            "spread-report": "signal",
        }
        rows = list(ledger.rows(kind=kinds.get(which), limit=20))
        print(f"{which}: last {len(rows)} ledger rows"
              f" (chain: {'OK' if ledger.verify().ok else 'BROKEN'})")
        for row in rows[:10]:
            print(f"  #{row.seq} {row.ts_utc} {row.kind} corr={row.correlation_id}")
        return 0
    finally:
        ledger.close()


def backtest_cli(root: Path, strategy: str, symbol: str) -> int:
    from aegis_velocity.audit.stats import expectancy, profit_factor
    from aegis_velocity.backtest.tick_engine import StressConfig, run_strategy_over_ticks

    cfg = load_desk_config(root)
    if strategy not in cfg.strategies.strategies:
        print(f"unknown strategy {strategy}")
        return 1
    ticks = load_recorded_ticks(root / "data" / "ticks", symbol)
    if len(ticks) < 500:
        print(f"INSUFFICIENT_DATA: {len(ticks)} recorded ticks for {symbol} "
              "(need >= 500). Record ticks first (record-ticks). Bar backtests are "
              "NON-EVIDENCE and are not offered.")
        return 1
    spec = default_spec(symbol)
    strategy_cfg = cfg.strategies.strategies[strategy]

    def make_signals(window: tuple[Tick, ...]) -> list[Any]:
        ctx = StrategyContext(
            strategy_id=strategy, symbol=symbol, spec=spec, ticks=window, bars=(),
            server_now=window[-1].time, cfg=strategy_cfg,
        )
        return STRATEGY_REGISTRY[strategy](ctx)

    for label, stress in (("base", None), ("stressed", StressConfig.stressed())):
        result = run_strategy_over_ticks(
            strategy, spec, ticks, make_signals, stress=stress,
        )
        rs = result.returns_r
        print(
            f"[{label}] {strategy}/{symbol}: fills={len(rs)} "
            f"signals={result.signals_seen} untriggered={result.signals_untriggered} "
            f"expectancy={expectancy(rs):.4f}R PF={profit_factor(rs):.3f}"
            if rs else f"[{label}] no fills — INSUFFICIENT_DATA for any verdict"
        )
    print("NOTE: tick source is "
          + ("SIM-RECORDED (non-evidence for live promotion)" if True else "live"))
    return 0


def walkforward_cli(root: Path, strategy: str) -> int:
    from aegis_velocity.pipeline.promotion import (
        WalkForwardEvidence,
        pipeline_verdict,
        walkforward_gate,
    )

    print(f"walk-forward for {strategy}: gathering OOS evidence from recorded ticks…")
    evidence = WalkForwardEvidence(oos_returns_r=[])
    gates = walkforward_gate(evidence)
    for g in gates:
        print(f"  [{g.outcome.value:>17}] {g.name}: {g.detail}")
    print(f"verdict: {pipeline_verdict(gates).value}")
    return 0


def calendar_import_cli(root: Path, csv_path: Path) -> int:
    count = import_calendar_csv(csv_path, root / "data" / "calendar.json")
    print(f"imported {count} calendar events")
    return 0


def positions_cli(root: Path, which: str) -> int:
    desk = build_desk(root, TradingMode.SHADOW)
    try:
        if which == "positions":
            for p in desk.gateway.call(P2_ACCOUNT, "positions_get"):
                print(f"  #{p.ticket} {p.symbol} {p.side.value} {p.volume} "
                      f"@{p.price_open} sl={p.sl} tp={p.tp} pnl={p.profit:.2f}")
            print("(no positions)" if not desk.gateway.call(P2_ACCOUNT, "positions_get")
                  else "")
        elif which == "pendings":
            orders = desk.gateway.call(P2_ACCOUNT, "orders_get")
            for o in orders:
                print(f"  #{o.ticket} {o.symbol} {o.kind.value} {o.volume} @{o.price}")
            if not orders:
                print("(no pending orders)")
        elif which == "reconcile":
            from aegis_velocity.execution.reconcile import startup_reconcile

            report = startup_reconcile(
                desk.gateway, desk.ledger, desk.intents,
                now_fn=lambda: datetime.now(UTC),
            )
            print(f"reconcile: {report}")
        elif which == "ea-status":
            print("EA bridge not running in this CLI invocation; "
                  "ea-status is meaningful inside `run` on the trading host.")
        return 0
    finally:
        desk.stop()


def activate_live_cli(root: Path) -> int:
    """HUMAN-ONLY (TTY enforced by cli.py). Full §13 arming ceremony."""
    cfg = load_desk_config(root)
    available, detail = real_client_available()
    if not available:
        print(f"activate-live requires the real MT5 terminal: {detail}")
        print("USER-ACTION: run this on the Windows trading host.")
        return 1
    if not cfg.env.live_trading_enabled:  # pragma: no cover - real host only
        print("LIVE_TRADING_ENABLED is not true in .env — refusing.")
        return 1
    # pragma: no cover start (interactive, real host only)
    desk = build_desk(root, TradingMode.LIVE_CANARY)
    try:
        info = desk.gateway.call(P2_ACCOUNT, "account_info")
        if info is None:
            print("no account info; aborting")
            return 1
        if info.login not in (cfg.env.live_account_allowlist or ()):
            print("account not in LIVE_ACCOUNT_ALLOWLIST — refusing")
            return 1
        if info.margin_mode != "HEDGING" or not info.trade_allowed or info.is_investor:
            print("account fails hedging/permission checks — refusing")
            return 1
        print(f"account {mask_login(info.login)} @ {info.server} "
              f"balance={info.balance:.2f} equity={info.equity:.2f}")
        print(f"limits: {cfg.risk.model_dump()}")
        verify = desk.ledger.verify()
        print(f"self-tests: ledger={'OK' if verify.ok else 'FAIL'}")
        if not verify.ok:
            return 1
        typed = getpass.getpass(f"type the phrase to arm ({ARMING_PHRASE!r}): ")
        if typed != ARMING_PHRASE:
            print("phrase mismatch — NOT armed")
            return 1
        token = write_token(root / "data" / "arming.json", info.login, info.server,
                            "LIVE_CANARY", cfg.config_hash())
        desk.ledger.append("arming", {"account": mask_login(info.login),
                                      "server": info.server, "mode": token.mode,
                                      "config_hash": token.config_hash})
        print("ARMED (LIVE_CANARY): first fills are min-lot canary. Red banner active.")
        return 0
    finally:
        desk.stop()
    # pragma: no cover end


def promote_live_full_cli(root: Path) -> int:
    """HUMAN-ONLY. Exits canary only after the §11 canary gate passes."""
    cfg = load_desk_config(root)
    data = root / "data"
    counters = PersistedCounters(PersistedState(data / "counters.json"))
    fills = counters.get_int("canary_fills")
    if fills < cfg.risk.canary_fills:
        print(f"canary gate NOT passed: {fills}/{cfg.risk.canary_fills} min-lot fills")
        return 1
    status = validate_token(
        data / "arming.json", cfg.env.login or 0, cfg.env.server, cfg.config_hash()
    )
    if not status.armed:
        print(f"not armed: {status.reason}")
        return 1
    write_token(data / "arming.json", cfg.env.login or 0, cfg.env.server, "LIVE",
                cfg.config_hash())
    print("promoted to LIVE full sizing (arming token updated).")
    return 0


def desk_status_snapshot(desk: Desk) -> dict[str, Any]:
    info = desk.client.account_info()
    metrics = desk.gateway.metrics()
    return {
        "mode": desk.mode.value + (" [SIM]" if desk.is_sim else ""),
        "account": mask_login(info.login) if info else "?",
        "server": info.server if info else "?",
        "balance": info.balance if info else 0.0,
        "equity": info.equity if info else 0.0,
        "margin_level": info.margin_level if info else 0.0,
        "gateway_calls": metrics.calls_total,
        "gateway_queue": metrics.queue_depth,
        "latency_p50_ms": metrics.latency_p50_ms,
        "cost_burn_today": desk.cost_engine.burn.total_costs,
        "gross_today": desk.cost_engine.burn.total_gross,
        "ts": datetime.now(UTC).isoformat(),
    }
